# Generated by Django 4.0.1 on 2022-01-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_entregas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregas',
            options={'verbose_name_plural': 'Entregas'},
        ),
    ]
