# Generated by Django 4.0.1 on 2022-01-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_entregas', '0002_alter_entregas_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregas',
            name='valor_currency',
        ),
        migrations.AlterField(
            model_name='entregas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
