# Generated by Django 4.0.1 on 2022-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_entregas', '0003_remove_entregas_valor_currency_alter_entregas_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
